ina: /assets
exa: https://dl.dropboxusercontent.com/u/19851056/0
exclude: [ 'Gemfile' ]
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
paginate: 5
highlighter: rouge

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
