exclude: [ 'Gemfile' ]
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "no_intra_emphasis", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
paginate: 5
highlighter: pygments

permalink: /blog/:year/:month/:day/:title/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
