ina: /assets
exa: http://d.physino.xyz/u/19851056/0
exclude: [ 'Gemfile' ]
markdown: redcarpet
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "no_intra_emphasis", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
paginate: 5
highlighter: pygments

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
