# https://jekyllrb.com/docs/configuration/#default-configuration
ina: /assets
exa: https://dl.dropboxusercontent.com/s/9zy32n82ppo0hj6

paginate: 5
plugins: [jekyll-paginate]

permalink: pretty

# https://jekyllrb.com/docs/configuration/#front-matter-defaults
# "path" is mendatory to define a scope. "type" is optional, it can be chosen
# from "posts", "pages", "drafts", or a self-defined collection.
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
